//ADMIN
CREATE USER RSPONSABILE_ADMIN IDENTIFIED BY admin;
GRANT ALL PRIVILEGES to RESPONSABILE_ADMIN;
GRANT CONNECT, CREATE SESSION TO RESPONSABILE_ADMIN;

//DIPENDENTE
CREATE USER DIPENDENTE IDENTIFIED BY Ndipendente;
GRANT CONNECT, CREATE SESSION TO DIPENDENTE;
GRANT SELECT, DELETE, UPDATE ON INVENTARIO TO DIPENDENTE;
GRANT SELECT, DELETE, UPDATE ON TURNO TO DIPENDENTE;
GRANT SELECT, DELETE, UPDATE ON COMPRENDE TO DIPENDENTE;
GRANT SELECT, DELETE, UPDATE ON CONTIENE TO DIPENDENTE;
GRANT SELECT, DELETE, UPDATE ON COSTITUITO TO DIPENDENTE;
GRANT SELECT, DELETE, UPDATE ON POSSIEDE TO DIPENDENTE;
GRANT SELECT, DELETE, UPDATE ON ABBONAMENTO TO DIPENDENTE;
GRANT SELECT, DELETE, UPDATE ON PRODOTTO TO DIPENDENTE;
GRANT SELECT, DELETE, UPDATE ON SOCIETA TO DIPENDENTE;
GRANT SELECT, DELETE, UPDATE ON PROMOZIONE TO DIPENDENTE;
GRANT SELECT, DELETE, UPDATE ON AUTORE TO DIPENDENTE;
GRANT SELECT, DELETE, UPDATE ON STATO_ACQUISTO TO DIPENDENTE;
GRANT SELECT, DELETE, UPDATE ON STATO_SPEDIZIONE TO DIPENDENTE;
GRANT SELECT, DELETE, UPDATE ON SPEDIZIONE TO DIPENDENTE;
GRANT SELECT, DELETE, UPDATE ON ACQUISTO TO DIPENDENTE;
GRANT SELECT, DELETE, UPDATE ON METODO_DI_PAGAMENTO TO DIPENDENTE;
GRANT SELECT, DELETE, UPDATE ON INDIRIZZO TO DIPENDENTE;
GRANT SELECT, DELETE, UPDATE ON CLIENTE TO DIPENDENTE;
GRANT EXECUTE ON VENDITE_PRODOTTI TO DIPENDENTE;
GRANT EXECUTE ON TOTALE_ACQUISTO TO DIPENDENTE;
GRANT EXECUTE ON INSERIMENTO_INDIRIZZO TO DIPENDENTE;
GRANT EXECUTE ON CANCELLAZIONE_ACQUISTO TO DIPENDENTE;
GRANT SELECT VIEW_ORDINI TO DIPENDENTE;

//CLIENTE
CREATE USER CLIENTE IDENTIFIED BY Ncliente;
GRANT CONNECT TO CLIENTE;
GRANT SELECT VIEW_ORDINI TO CLIENTE;
GRANT EXECUTE ON INSERIMENTO_INDIRIZZO TO CLIENTE;
GRANT EXECUTE ON CANCELLAZIONE_ACQUISTO TO CLIENTE;

