CREATE OR REPLACE VIEW VIEW_ORDINI AS
SELECT
    CLIENTE.CODICE_FISCALE,
    ACQUISTO.N_ACQUISTO,
    PRODOTTO.ID_PRODOTTO,
    PRODOTTO.NOME_PRODOTTO,
    PRODOTTO.PREZZO_PRODOTTO,
    CONTIENE.QUANTITA,
    METODO_DI_PAGAMENTO.CODICE_IDENTIFICATIVO,
    INDIRIZZO.QUALIFICATORE,
    INDIRIZZO.STRADA,
    INDIRIZZO.NUMERO,
    INDIRIZZO.CITTA,
    INDIRIZZO.PROVINCIA,
    INDIRIZZO.CAP,
    INDIRIZZO.STATO_EUROPEO,
    SPEDIZIONE.N_SPEDIZIONE,
    STATO_SPEDIZIONE.DATA_STATO_SPEDIZIONE,
    STATO_SPEDIZIONE.STATO_SPEDIZIONE
FROM
    CLIENTE
    JOIN METODO_DI_PAGAMENTO ON CLIENTE.CODICE_FISCALE = METODO_DI_PAGAMENTO.CODICE_FISCALE_MDP
    JOIN ACQUISTO ON CLIENTE.CODICE_FISCALE = ACQUISTO.CODICE_FISCALE_ACQUISTO
    JOIN CONTIENE ON ACQUISTO.N_ACQUISTO = CONTIENE.N_ACQUISTO_CONTIENE
    JOIN SPEDIZIONE ON ACQUISTO.N_ACQUISTO = SPEDIZIONE.N_ACQUISTO_SPEDIZIONE
    JOIN INDIRIZZO ON SPEDIZIONE.INDIRIZZO_SPEDIZIONE = INDIRIZZO.ID_INDIRIZZO
    JOIN STATO_SPEDIZIONE ON SPEDIZIONE.N_SPEDIZIONE = STATO_SPEDIZIONE.N_SPEDIZIONE_STATO_SPEDIZIONE
    JOIN PRODOTTO ON CONTIENE.ID_PRODOTTO_CONTIENE = PRODOTTO.ID_PRODOTTO;
